export const services = [
  {
    id: "bridal-glam",
    name: "Bridal Glam",
    category: "Bridal",
    duration: "120 min",
    price: 220,
    short: "Soft glam tailored for your big day.",
    description:
      "A signature bridal look crafted around your features, skin tone and wedding palette. Includes complimentary skin prep and trial consultation notes.",
    includes: ["Skin prep & prime", "Long-wear foundation", "Soft glam eyes", "Lash application", "Touch-up kit"],
    rating: 4.9,
    reviews: 218,
    hue: "from-[#F8D7DA] to-[#E8B4BC]",
  },
  {
    id: "party-makeup",
    name: "Evening Glam",
    category: "Party",
    duration: "75 min",
    price: 95,
    short: "Statement looks for nights to remember.",
    description: "Bold, photo-ready makeup designed for evening events, dinners and parties.",
    includes: ["Full coverage base", "Cut crease eyes", "Lash strip", "Contour & highlight"],
    rating: 4.8,
    reviews: 134,
    hue: "from-[#FCEEEF] to-[#E8B4BC]",
  },
  {
    id: "natural-glow",
    name: "Natural Glow",
    category: "Everyday",
    duration: "45 min",
    price: 60,
    short: "Effortless 'your skin but better' finish.",
    description: "A soft, dewy everyday look that lets your natural features shine.",
    includes: ["Tinted base", "Cream blush", "Brow grooming", "Glossy lip"],
    rating: 4.9,
    reviews: 312,
    hue: "from-[#FFF1E6] to-[#F8C8C0]",
  },
  {
    id: "engagement",
    name: "Engagement Look",
    category: "Bridal",
    duration: "90 min",
    price: 150,
    short: "Romantic and luminous, ring-ready.",
    description: "A soft romantic look with a luminous base and rosy tones.",
    includes: ["Hydrating prep", "Soft glam eyes", "Lashes", "Rose lip"],
    rating: 4.7,
    reviews: 89,
    hue: "from-[#FBE3E8] to-[#D89AA4]",
  },
  {
    id: "skincare-facial",
    name: "Glow Facial",
    category: "Skincare",
    duration: "60 min",
    price: 80,
    short: "Hydration + glow in one session.",
    description: "Cleanse, exfoliate, mask and massage for visibly glowing skin.",
    includes: ["Deep cleanse", "Enzyme exfoliation", "Hydrating mask", "Facial massage"],
    rating: 4.8,
    reviews: 176,
    hue: "from-[#F4E1DC] to-[#E2B4A8]",
  },
  {
    id: "hair-styling",
    name: "Hair Styling",
    category: "Hair",
    duration: "60 min",
    price: 70,
    short: "Soft curls, sleek blowouts, updos.",
    description: "Professional styling for events, parties and shoots.",
    includes: ["Wash & blow dry", "Heat protection", "Styling of choice"],
    rating: 4.7,
    reviews: 142,
    hue: "from-[#F1DADA] to-[#C97C8A]",
  },
];

export const categories = [
  { name: "Bridal", emoji: "💍" },
  { name: "Party", emoji: "✨" },
  { name: "Everyday", emoji: "🌸" },
  { name: "Skincare", emoji: "🧖‍♀️" },
  { name: "Hair", emoji: "💇‍♀️" },
  { name: "Nails", emoji: "💅" },
];
