export const servicesData = [
  // ================= Hairstyle =================
  {
    id: 1,
    name: "Simple Front Hairstyle",
    category: "Hairstyle",
    price: 150,
    duration: "30 min",
    icon: "💇‍♀️",
  },
  {
    id: 2,
    name: "Simple Back Hairstyle",
    category: "Hairstyle",
    price: 250,
    duration: "45 min",
    icon: "✨",
  },
  {
    id: 3,
    name: "Heavy & Stylish Hairstyle",
    category: "Hairstyle",
    price: 350,
    duration: "60 min",
    icon: "👑",
  },

  // ================= Makeup =================
  {
    id: 4,
    name: "Sider Makeup",
    category: "Makeup",
    price: 700,
    duration: "45 min",
    icon: "💄",
  },
  {
    id: 5,
    name: "Party Makeup",
    category: "Makeup",
    price: 800,
    duration: "60 min",
    icon: "💋",
  },
  {
    id: 6,
    name: "Mehandi Makeup",
    category: "Makeup",
    price: 800,
    duration: "60 min",
    icon: "🌿",
  },
  {
    id: 7,
    name: "Haldi Makeup",
    category: "Makeup",
    price: 900,
    duration: "60 min",
    icon: "🌼",
  },
  {
    id: 8,
    name: "Cocktail Party Look",
    category: "Makeup",
    price: 1200,
    duration: "90 min",
    icon: "🍸",
  },
  {
    id: 9,
    name: "Engagement Makeup",
    category: "Bridal",
    price: 1500,
    duration: "90 min",
    icon: "💍",
  },
  {
    id: 10,
    name: "Bridal Makeup",
    category: "Bridal",
    price: 3000,
    duration: "180 min",
    icon: "👰",
  },
  {
    id: 11,
    name: "Reception Makeup",
    category: "Bridal",
    price: 4000,
    duration: "180 min",
    icon: "✨",
  },
  {
    id: 12,
    name: "HD Makeup",
    category: "Premium",
    price: 5000,
    duration: "210 min",
    icon: "💎",
  },
];
